MyBookingRoles/Models/Rentals/Studio.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema; 
using System.Linq;
using System.Web;

namespace MyBookingRoles.Models.Rentals
{
    public class Studio
    {
        public int StudioId { get; set; }

        [Display(Name ="Studio")]
        public string StudioName { get; set; }

        //public int Capacity { get; set; }

        [Display(Name = "Price per hour (R)*")]
        [ScaffoldColumn(true)]
        [DataType(DataType.Currency)]
        public double StudioPrice { get; set; }

        [Display(Name = "Preview Studio Image")]
        public byte[] StudioPics { get; set; }


        //public double TotStudioPrice { get; set; }

        public virtual ICollection<Rental> Rentals { get; set; }

       

    }
}

MyBookingRoles/Controllers/Rentals/StudiosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyBookingRoles.Models;
using MyBookingRoles.Models.Rentals;

namespace MyBookingRoles.Controllers.Rentals
{
    [Authorize(Roles = "SuperAdmin")]
    public class StudiosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Studios
        public ActionResult Index()
        {
            return View(db.Studios.ToList());
        }



        // GET: Studios/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studio studio = db.Studios.Find(id);
            if (studio == null)
            {
                return HttpNotFound();
            }
            return View(studio);
        }

        // GET: Studios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Studios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "StudioId,StudioName,StudioPrice,StudioPics")] Studio studio, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                //Added
                if (file != null)
                {
                    studio.StudioPics = new byte[file.ContentLength];
                    file.InputStream.Read(studio.StudioPics, 0, file.ContentLength);
                }
                db.Studios.Add(studio);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(studio);
        }

        // GET: Studios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studio studio = db.Studios.Find(id);
            if (studio == null)
            {
                return HttpNotFound();
            }
            return View(studio);
        }

        // POST: Studios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "StudioId,StudioName,StudioPrice,StudioPics")] Studio studio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studio).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(studio);
        }

        // GET: Studios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Studio studio = db.Studios.Find(id);
            if (studio == null)
            {
                return HttpNotFound();
            }
            return View(studio);
        }

        // POST: Studios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Studio studio = db.Studios.Find(id);
            db.Studios.Remove(studio);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyBookingRoles/Views/Studios/Create.cshtml
@model MyBookingRoles.Models.Rentals.Studio

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Create Rental Studio</h2>

@using (Html.BeginForm("Create", "Studios", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.StudioName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudioName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StudioName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StudioPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StudioPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StudioPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StudioPics, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control" />
            @Html.ValidationMessageFor(model => model.StudioPics, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Rent Studio" class="btn btn-success" />
        </div>
    </div>
</div>
}

<div>
    <hr />
    @Html.ActionLink("Back to List", "Index", null,new { @class = "btn btn-primary" })
</div>

MyBookingRoles/Views/Studios/Delete.cshtml
@model MyBookingRoles.Models.Rentals.Studio

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    var base64 = "";
    var imgsrc = "";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this Studio?</h3>
<div>
    <h4>Studio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudioPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudioPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudioPics)
        </dt>

        <dd>
            @if (Model.StudioPics != null)
            {
                base64 = Convert.ToBase64String(Model.StudioPics);
                imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                <img src='@imgsrc' style="width:100px;height:100px" class="img-rounded" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyBookingRoles/Views/Studios/Details.cshtml
@model MyBookingRoles.Models.Rentals.Studio

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    var base64 = "";
    var imgsrc = "";
}

<h2>Details</h2>

<div>
    <h4>Studio</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.StudioName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudioName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudioPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.StudioPrice)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.StudioPics)
        </dt>

        <dd>
            @if (Model.StudioPics != null)
            {
                base64 = Convert.ToBase64String(Model.StudioPics);
                imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                <img src='@imgsrc' style="width:100px;height:100px" class="img-rounded" />
            }
        </dd>

    </dl>
</div>
<p>
    @*@Html.ActionLink("Edit", "Edit", new { id = Model.StudioId }) |*@
    @Html.ActionLink("Back to Studios", "Index", new { @class = "btn btn-info" })
</p>

MyBookingRoles/Views/Studios/Edit.cshtml
@model MyBookingRoles.Models.Rentals.Studio

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Studio</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.StudioId)

        <div class="form-group">
            @Html.LabelFor(model => model.StudioName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudioName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudioName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudioPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudioPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudioPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StudioPics, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StudioPics, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudioPics, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyBookingRoles/Views/Studios/Index.cshtml
@model IEnumerable<MyBookingRoles.Models.Rentals.Studio>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>All Studios</h2>

<p>
    @Html.ActionLink("Create New", "Create",null, new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.StudioName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudioPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StudioPics)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var base64 = "";
        var imgsrc = "";

        <tr style="text-align:center">
            <td>
                @Html.DisplayFor(modelItem => item.StudioName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudioPrice)
            </td>
            <td>
                @if (item.StudioPics != null)
                {
                    base64 = Convert.ToBase64String(item.StudioPics);
                    imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                    <img src='@imgsrc' style="width:50px;height:50px" class="img-responsive" />
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.StudioId }, new { @class = "btn btn-default" }) |
                @Html.ActionLink("Details", "Details", new { id = item.StudioId }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.StudioId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
<hr />
@Html.ActionLink("Return To SuperAdmin", "Index", "SuperAdmin", null, new { @class = "btn btn-primary" })