MyBookingRoles/Models/Rentals/Equipment.cs
using MyBookingRoles.Models.Store;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MyBookingRoles.Models.Rentals
{
    public class Equipment
    {
        [Key]
        public int EquipId { get; set; }

        [Display(Name = "Equipment")]
        public string EquipName { get; set; }

        //public int Capacity { get; set; }

        [Display(Name = "Price for Hire (R)*")]
        [ScaffoldColumn(true)]
        [DataType(DataType.Currency)]
        public double Price { get; set; }

        [Display(Name = "Preview Equipment Image")]
        public byte[] EquipPics { get; set; }

        public int BrandID { get; set; }

        [Display(Name = "Product Category")]
        public int CategoryID { get; set; }

        [ForeignKey("CategoryID")]
        [Display(Name = "Product Category")]
        public virtual Category Category { get; set; }

        public virtual Brand Brand { get; set; }

        public virtual ICollection<EqRental> EqRentals { get; set; }

    }
}

MyBookingRoles/Controllers/Rentals/EquipmentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyBookingRoles.Models;
using MyBookingRoles.Models.Rentals;

namespace MyBookingRoles.Controllers.Rentals
{
    [Authorize(Roles ="SuperAdmin")]
    public class EquipmentsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Equipments
        public ActionResult Index()
        {
            var equipment = db.Equipment.Include(e => e.Brand).Include(e => e.Category);
            return View(equipment.ToList());
        }

        
        // GET: Equipments/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipment equipment = db.Equipment.Find(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        // GET: Equipments/Create
        public ActionResult Create()
        {
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "Name");
            ViewBag.CategoryID = new SelectList(db.Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Equipments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EquipId,EquipName,Price,EquipPics,BrandID,CategoryID")] Equipment equipment, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                //Added
                if (file != null)
                {
                    equipment.EquipPics = new byte[file.ContentLength];
                    file.InputStream.Read(equipment.EquipPics, 0, file.ContentLength);
                }
                db.Equipment.Add(equipment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "Name", equipment.BrandID);
            ViewBag.CategoryID = new SelectList(db.Category, "CategoryId", "CategoryName", equipment.CategoryID);
            return View(equipment);
        }

        // GET: Equipments/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipment equipment = db.Equipment.Find(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "Name", equipment.BrandID);
            ViewBag.CategoryID = new SelectList(db.Category, "CategoryId", "CategoryName", equipment.CategoryID);
            return View(equipment);
        }

        // POST: Equipments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "EquipId,EquipName,Price,EquipPics,BrandID,CategoryID")] Equipment equipment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(equipment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.BrandID = new SelectList(db.Brands, "BrandID", "Name", equipment.BrandID);
            ViewBag.CategoryID = new SelectList(db.Category, "CategoryId", "CategoryName", equipment.CategoryID);
            return View(equipment);
        }

        // GET: Equipments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Equipment equipment = db.Equipment.Find(id);
            if (equipment == null)
            {
                return HttpNotFound();
            }
            return View(equipment);
        }

        // POST: Equipments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Equipment equipment = db.Equipment.Find(id);
            db.Equipment.Remove(equipment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MyBookingRoles/Views/Equipments/Create.cshtml
@model MyBookingRoles.Models.Rentals.Equipment

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

    <h2>Create Equipment</h2>

@using (Html.BeginForm("Create", "Equipments", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.EquipName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EquipName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EquipName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EquipPics, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control" />
            @Html.ValidationMessageFor(model => model.EquipPics, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BrandID, "BrandID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BrandID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BrandID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    <hr />
    @Html.ActionLink("Back to List", "Index",null, new { @class = "btn btn-primary" })
</div>

MyBookingRoles/Views/Equipments/Delete.cshtml
@model MyBookingRoles.Models.Rentals.Equipment

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Equipment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquipPics)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquipPics)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MyBookingRoles/Views/Equipments/Details.cshtml
@model MyBookingRoles.Models.Rentals.Equipment

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
    var base64 = "";
    var imgsrc = "";
}

<h2>Details</h2>

<div>
    <h4>Equipment</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquipName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EquipName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EquipPics)
        </dt>

        <dd>
            @if (Model.EquipPics != null)
            {
                base64 = Convert.ToBase64String(Model.EquipPics);
                imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                <img src='@imgsrc' style="width:100px;height:100px" class="img-rounded" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.EquipId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MyBookingRoles/Views/Equipments/Edit.cshtml
@model MyBookingRoles.Models.Rentals.Equipment

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm("Create", "Equipments", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Equipment</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.EquipId)

    <div class="form-group">
        @Html.LabelFor(model => model.EquipName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EquipName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EquipName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EquipPics, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="file" name="file" id="file" class="form-control" />
            @Html.ValidationMessageFor(model => model.EquipPics, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BrandID, "BrandID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("BrandID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.BrandID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MyBookingRoles/Views/Equipments/Index.cshtml
@model IEnumerable<MyBookingRoles.Models.Rentals.Equipment>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_UserLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
</p>
<table class="table table-responsive table-hover table-condensed" id="UsersWithRoles">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Brand.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EquipName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EquipPics)
        </th>
        <th style="background-color: gray;text-align:center;">Actions</th>
    </tr>

    @foreach (var item in Model)
    {
        var base64 = "";
        var imgsrc = "";

        <tr style="text-align:center">
            <td>
                @Html.DisplayFor(modelItem => item.Brand.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Category.CategoryName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EquipName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @if (item.EquipPics != null)
                {
                    base64 = Convert.ToBase64String(item.EquipPics);
                    imgsrc = string.Format("data:image/gif;base64,{0}", base64);

                    <img src='@imgsrc' style="width:100px;height:100px" class="img-responsive" />
                }
            </td>
            <td style="text-align:center;">
                @Html.ActionLink("Edit", "Edit", new { id = item.EquipId }, new { @class = "btn btn-default" }) |
                @Html.ActionLink("Details", "Details", new { id = item.EquipId }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.EquipId }, new { @class = "btn btn-danger" })
            </td>
        </tr>
    }

</table>
<hr />
@Html.ActionLink("Return To SuperAdmin", "Index", "SuperAdmin", null, new { @class = "btn btn-primary" })